[package]
name = "nassau-wasm"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
nassau_core = { path = "../core" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5" 