[package]
name = "nassau-wasm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
wasm-pack = { version = "0.14", optional = true}

[workspace]
resolver="2"
members= [
    "crates/core",
    "crates/wasm"
]
